### ISSUE TITLE
Breakpoint ignored because generated code not found (source map problem?)

### ISSUE THREAD

**Issue by nazar322** [frederiksen/angular-electron-boilerplate#4]
Having launched `Main + Renderer` profile VSCode can't hit breakpoints set in a `.ts` file for the renderer process.
It says `Breakpoint ignored because generated code not found (source map problem?)`
Breakpoints set in `main.ts` work.
![image](https://user-images.githubusercontent.com/10635299/77540432-c2823e80-6eab-11ea-864c-7f36f0094791.png)
![image](https://user-images.githubusercontent.com/10635299/77540456-c9a94c80-6eab-11ea-895d-994c040452cf.png)

**Comment by frederiksen** [comment]
Could be that the launch.json file need tweaking. Try reading this: https://github.com/frederiksen/angular-electron-boilerplate/issues/2

**Comment by nazar322** [comment]
The `launch.json` is original except port numbers for both profiles and in the debug output I see the verbose output so the debugger attached properly (renderer process).

It must be a source map problem because what I did is I navigated to `.dist\main` folder and removed `electron-main.js.map`. After that, I started the main process debugging and the breakpoint that used to work did not hit and the VS showed the same notification about breakpoint being ignored. I then restored the `electron-main.js.map` and it started to break and work again.

I am new to this but I think there must be the same corresponding map files for .ts files in the renderer process. I will dig towards `tsc` as it should generate map files if I'm not mistaking.

@frederiksen  Can you hit the same breakpoint as on my screenshot on your end (app.component.ts line 16)?

**Comment by nazar322** [comment]
I managed to find a solution.
Go to `launch.json` and change line #17 to `"webpack:///./*": "${workspaceRoot}/src/renderer/*"`
